name: zoonsk
description: A new Flutter project.

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'


dependencies:
 
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.7
  dio: ^5.4.0
  simple_circular_progress_bar: ^1.0.2
  spider: ^4.2.2
  audioplayers: ^5.2.1
  table_calendar: ^3.0.9
  retrofit: ^4.0.3
  json_annotation: ^4.8.1
  flutter_dotenv: ^5.1.0
  mobile_scanner: ^3.5.6
  
 
  
  


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  retrofit_generator: ^8.0.6
  json_serializable: ^6.7.1
  
 


  flutter_lints: ^2.0.0

flutter:

  
  uses-material-design: true

  
  assets:
  - assets/svg/
  - assets/image/
  - assets/sound/
  
  

  fonts:
   - family:  ZooIcons
     fonts:
     - asset: assets/fonts/ZooIcons.ttf
   - family:  museo
     fonts:
     - asset: assets/fonts/museocyrl.ttf
   - family:  Museo700
     fonts:
     - asset: assets/fonts/Museo Cyrl 700.ttf
   - family:  Museo300
     fonts:
     - asset: assets/fonts/Museo Cyrl 300.ttf

       
  
